name: GPU on manual trigger

on:
  workflow_dispatch

jobs:
  test_gpu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U anyscale pyyaml
    - name: Print environment info
      run: |
        ./xgboost_ray/tests/env_info.sh
    - name: Set anyscale project
      env:
        ANYSCALE_PROJECT: ${{ secrets.ANYSCALE_PROJECT }}
      run: |
        echo "project_id: ${ANYSCALE_PROJECT}" > ./xgboost_ray/tests/release/.anyscale.yaml
    - name: Run end to end GPU test
      env:
        ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
      run: |
        pushd ./xgboost_ray/tests/release
        ./run_e2e_gpu.sh
        popd || true
